### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Cotino** [lucasg/powershell-docset#2]
Hi, 
first of all i don't use python, so i struggled a lot to install dependencies and such, but i finally managed to install pip and the dependencies, except for phantomJS. 
pip gives me the error :
```
Could not find a version that satisfies the requirement phantomjs (from versions: )
No matching distribution found for phantomjs.
```

When compiling, i get this error : 
```
Traceback (most recent call last):
  File "c:\Users\RODRIGN1\Desktop\toto\Bazar\Portable\powershell-docset-master\posh-to-dash.py", line 716, in <module>
    conf = Configuration( args )
  File "c:\Users\RODRIGN1\Desktop\toto\Bazar\Portable\powershell-docset-master\posh-to-dash.py", line 123, in __init__
    self.webdriver = PoshWebDriver(args.phantom)
  File "c:\Users\RODRIGN1\Desktop\toto\Bazar\Portable\powershell-docset-master\posh-to-dash.py", line 46, in __init__
    firefox_options=options
  File "C:\Users\RODRIGN1\Desktop\toto\Bazar\Portable\Python 3.6.5\App\Python\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    keep_alive=True)
  File "C:\Users\RODRIGN1\Desktop\toto\Bazar\Portable\Python 3.6.5\App\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\RODRIGN1\Desktop\toto\Bazar\Portable\Python 3.6.5\App\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\RODRIGN1\Desktop\toto\Bazar\Portable\Python 3.6.5\App\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\RODRIGN1\Desktop\toto\Bazar\Portable\Python 3.6.5\App\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```
What do i do ?
Why isn't there a docset already compiled available ?
I just want a powershell docset to learn powershell.

**Comment by lucasg** [comment]
I installed `phantomjs` separately (it's not a python lib, it's an executable) and I launch the following command :

```
python.exe posh-to-dash.py --output=Powershell/versions/6/Powershell.tgz --version=6 --phantom=$(PATH_TO_PHANTOM_EXE)
```

But in your case just use the prebuilt docsets : https://github.com/lucasg/powershell-docset/releases.
Alternatively, the docset is present on `Velocity` and `Dash` (don't know about `Zeal`) :

![image](https://user-images.githubusercontent.com/2520861/43153257-0f38ca9e-8f71-11e8-9e8f-12002db3e6a5.png)
